use_frameworks!

target 'Tesfy_Example' do
  
  pod 'MurmurHash-Swift', '1.0.13'
  pod 'jsonlogic', '1.0.0'

  pod 'Tesfy', :path => '../'

  target 'Tesfy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
